
package com.cons.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProviderService", targetNamespace = "http://prov.com/", wsdlLocation = "http://localhost:9100/Service/Provider?wsdl")
public class ProviderService
    extends Service
{

    private final static URL PROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVIDERSERVICE_EXCEPTION;
    private final static QName PROVIDERSERVICE_QNAME = new QName("http://prov.com/", "ProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9100/Service/Provider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROVIDERSERVICE_WSDL_LOCATION = url;
        PROVIDERSERVICE_EXCEPTION = e;
    }

    public ProviderService() {
        super(__getWsdlLocation(), PROVIDERSERVICE_QNAME);
    }

    public ProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVIDERSERVICE_QNAME, features);
    }

    public ProviderService(URL wsdlLocation) {
        super(wsdlLocation, PROVIDERSERVICE_QNAME);
    }

    public ProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVIDERSERVICE_QNAME, features);
    }

    public ProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Provider
     */
    @WebEndpoint(name = "ProviderPort")
    public Provider getProviderPort() {
        return super.getPort(new QName("http://prov.com/", "ProviderPort"), Provider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Provider
     */
    @WebEndpoint(name = "ProviderPort")
    public Provider getProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://prov.com/", "ProviderPort"), Provider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVIDERSERVICE_EXCEPTION!= null) {
            throw PROVIDERSERVICE_EXCEPTION;
        }
        return PROVIDERSERVICE_WSDL_LOCATION;
    }

}
